name: shared
version: 0.1.0-dev.1

environment: { sdk: ">=2.17.0 <3.0.0" }
dependencies:
  {
    dart_style: ^2.2.4, equatable: ^2.0.5,
    orchestrator: ^2.2.0,
    recase: ^4.1.0,
    sealed_unions: ^3.0.3+1,
  }
dev_dependencies: { lint: ^1.10.0 }
