version: "3"

services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
      target: prod
    image: yourilieverdink/builders_server:${TAG:-latest}
    ports:
      - "8000:8080"
