app = 'architect'
primary_region = 'ams'

[build]
  dockerfile = './packages/architect_server/Dockerfile'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/_internal_/healthcheck"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
