name: architect
version: 0.1.0-dev.1
publish_to: none

environment: { sdk: ">=2.18.0 <3.0.0" }
dependencies:
  {
    dart_style: ^2.2.4,
    equatable: ^2.0.5,
    orchestrator: ^2.5.1,
    recase: ^4.1.0,
    sealed_unions: ^3.0.3+1,
  }
dev_dependencies: { lint: ^2.0.20 }
