name: architect_cli
version: 0.1.0-dev.1
publish_to: none

environment: { sdk: ">=2.18.0 <3.0.0" }
dependencies:
  {
    args: ^2.3.1,
    collection: ^1.17.0,
    equatable: ^2.0.5,
    http: ^1.2.0,
    sealed_unions: ^3.0.3+1,
  }
dev_dependencies: { lint: ^2.0.20 }
