version: "3"

services:
  server:
    build:
      context: ../../
      dockerfile: ./services/server/Dockerfile
      target: prod
    image: yourilieverdink/builders_server:${TAG:-latest}
    ports:
      - "8000:8000"
