name: server
version: 0.1.0-dev.1
publish_to: none

environment: { sdk: ">=2.17.0 <3.0.0" }
dependencies:
  {
    equatable: ^2.0.5, orchestrator: ^2.4.0,
    recase: ^4.1.0,
    shared: { path: ../../packages/shared },
    shelf_plus: ^1.5.0,
  }
dev_dependencies: { lint: ^1.10.0, test: ^1.21.4 }
