version: "3"

services:
  server:
    build:
      context: ../../
      dockerfile: ./packages/architect_server/Dockerfile
      target: prod
    image: yourilieverdink/architect:${TAG:-latest}
    ports:
      - "8000:8080"
