# Created with package:mono_repo v6.3.0
name: Dart CI
on:
  push:
    branches:
      - main
  pull_request:
defaults:
  run:
    shell: bash
env:
  PUB_ENVIRONMENT: bot.github
permissions: read-all

jobs:
  job_001:
    name: mono_repo self validate
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - name: mono_repo self validate
        run: dart pub global activate mono_repo 6.3.0
      - name: mono_repo self validate
        run: dart pub global run mono_repo generate --validate
  job_002:
    name: "analyze_and_format; PKG: packages/architect; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/architect;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/architect
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_architect_pub_upgrade
        name: packages/architect; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/architect
        run: dart pub upgrade
      - name: "packages/architect; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_architect_pub_upgrade.conclusion == 'success'"
        working-directory: packages/architect
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/architect; dart analyze --fatal-infos ."
        if: "always() && steps.packages_architect_pub_upgrade.conclusion == 'success'"
        working-directory: packages/architect
        run: dart analyze --fatal-infos .
  job_003:
    name: "analyze_and_format; PKG: packages/architect_cli; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/architect_cli;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/architect_cli
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_architect_cli_pub_upgrade
        name: packages/architect_cli; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/architect_cli
        run: dart pub upgrade
      - name: "packages/architect_cli; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_architect_cli_pub_upgrade.conclusion == 'success'"
        working-directory: packages/architect_cli
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/architect_cli; dart analyze --fatal-infos ."
        if: "always() && steps.packages_architect_cli_pub_upgrade.conclusion == 'success'"
        working-directory: packages/architect_cli
        run: dart analyze --fatal-infos .
  job_004:
    name: "analyze_and_format; PKG: packages/architect_server; `dart format --output=none --set-exit-if-changed .`, `dart analyze --fatal-infos .`"
    runs-on: ubuntu-latest
    steps:
      - name: Cache Pub hosted dependencies
        uses: actions/cache@4504faf7e9bcf8f3ed0bc863c4e1d21499ab8ef8
        with:
          path: "~/.pub-cache/hosted"
          key: "os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/architect_server;commands:format-analyze"
          restore-keys: |
            os:ubuntu-latest;pub-cache-hosted;sdk:stable;packages:packages/architect_server
            os:ubuntu-latest;pub-cache-hosted;sdk:stable
            os:ubuntu-latest;pub-cache-hosted
            os:ubuntu-latest
      - uses: dart-lang/setup-dart@6a218f2413a3e78e9087f638a238f6b40893203d
        with:
          sdk: stable
      - id: checkout
        uses: actions/checkout@d0651293c4a5a52e711f25b41b05b2212f385d28
      - id: packages_architect_server_pub_upgrade
        name: packages/architect_server; dart pub upgrade
        if: "always() && steps.checkout.conclusion == 'success'"
        working-directory: packages/architect_server
        run: dart pub upgrade
      - name: "packages/architect_server; dart format --output=none --set-exit-if-changed ."
        if: "always() && steps.packages_architect_server_pub_upgrade.conclusion == 'success'"
        working-directory: packages/architect_server
        run: "dart format --output=none --set-exit-if-changed ."
      - name: "packages/architect_server; dart analyze --fatal-infos ."
        if: "always() && steps.packages_architect_server_pub_upgrade.conclusion == 'success'"
        working-directory: packages/architect_server
        run: dart analyze --fatal-infos .
